apps/blog/urls.py
from blog.feeds import RecentFeed, TagFeed
from blog.views.admin import EntryPreview, Index as AdminIndex, EditEntry, \
    UploadImage, ListEntryImages, DeleteImage, SpamComments
from blog.views.archive import Archive
from blog.views.comments import AddComment, DeleteComment, Unsubscribe
from blog.views.entry import Entry
from blog.views.index import Index
from blog.views.tags import Tags
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('blog.views',

    # Blog index
    url(r'^(?:tag/(?P<tag>[^/]+)/)?(?:page/(?P<page>\d+)/)?$', Index.as_view(), name="index"),

    # Search
    url(r'^search/(?:page/(?P<page>\d+)/)?$', Index.as_view(search=True), name="search"),

    # View entry
    url(r'^post/(?P<id>\d+)/(?:(?P<slug>[^/]+)/?)?$', Entry.as_view(), name="entry"),

    # Archive
    url(r'^archive/(?:(?P<year>\d{4})/)?$', Archive.as_view(), name="archive"),

    # Comments
    # url(r'^add-comment/(?P<entry_id>\d+)/$', AddComment.as_view(), name="add_comment"),
    url(r'^delete-comment/(?P<comment_id>\d+)/$', DeleteComment.as_view(), name="delete_comment"),
    url(r'^unsubscribe/(?P<comment_id>\d+)/(?P<secret>\w{5})/$', Unsubscribe.as_view(), name="unsubscribe_from_notifications"),

    # Tags
    url(r'^tags/$', Tags.as_view(), name="tags"),

    # Admin
    url(r'^admin/$', AdminIndex.as_view(), name="admin_index"),
    url(r'^admin/preview/$', EntryPreview.as_view(), name="admin_preview_entry"),
    url(r'^admin/new/$', EditEntry.as_view(), name="admin_add_entry"),
    url(r'^admin/edit/(?P<entry_id>\d+)/$', EditEntry.as_view(), name="admin_edit_entry"),
    url(r'^admin/ajax/image/add$', UploadImage.as_view(), name="admin_add_image"),
    url(r'^admin/ajax/image/list/(?P<entry_id>\d+)$', ListEntryImages.as_view(), name="admin_list_images"),
    url(r'^admin/ajax/image/delete$', DeleteImage.as_view(), name="admin_delete_image"),
    url(r'^admin/spam$', SpamComments.as_view(), name="admin_spam"),

) + patterns('',
    url(r'^feeds/recent/$', RecentFeed()),
    url(r'^feeds/tag/(?P<tag>[^/]+)/$', TagFeed(), name="tag_feed"),
)

apps/blog/forms.py
from blog.models import Image, Comment
from django import forms
from django.forms import ModelForm
from django.forms.fields import EMPTY_VALUES
from django.utils.translation import ugettext_lazy as _
from tagging.forms import TagField
from tagging.models import Tag
import datetime


class ImagesWidget(forms.HiddenInput):
    
    def render(self, name, value, attrs=None):
        if isinstance(value, list):
            value = ",".join([str(v) for v in value])
        return super(ImagesWidget, self).render(name, value, attrs)
    

class ImagesField(forms.Field):
    
    widget = ImagesWidget
    
    def clean(self, value):        
        if self.required and value in EMPTY_VALUES:
            raise forms.ValidationError(self.error_messages['required'])
        values = value.split(",")
        try:
            values = [int(v) for v in values if v]
        except ValueError:
            raise forms.ValidationError(u"Values must be integers.")
        return values
            

def edit_string_for_tags(tags):
    names = []
    for tag in tags:
        name = tag.name
        if u',' in name or u' ' in name:
            names.append(u'"%s"' % name)
        else:
            names.append(name)
    return u','.join(names)


class EntryForm(forms.Form):

    success_message = _(u"Your changes were saved.")
    error_message = _(u"Please correct the indicated errors.")

    title = forms.CharField(max_length=300,
                            required=True,
                            widget=forms.TextInput({"class": "title",
                                                    "placeholder": _(u"Title")}),
                            label=_(u"Title"),
                            )

    slug = forms.CharField(max_length=300,
                           required=False,
                           widget=forms.TextInput({"class": "slug",
                                                 "placeholder": _(u"Slug")}),
                           label=_(u"Slug"))

    text = forms.CharField(required=True,
                           widget=forms.Textarea({"class": "text markitup",
                                                  "placeholder": _(u"Text")}),
                           label=_(u"Text"),
                           )

    markdown = forms.BooleanField(required=False, initial=True,
                                   widget=forms.CheckboxInput({"class": "checkbox"}),
                                   label=_(u"Markdown"),
                                   )

    images = ImagesField(required=False,
                         label=_(u"Images"),
                         )

    published = forms.BooleanField(required=False, initial=False,
                                   widget=forms.CheckboxInput({"class": "checkbox"}),
                                   label=_(u"Published"),
                                   )
    publication_date = forms.DateField(required=False, input_formats=['%d.%m.%Y'],
                                       label=_(u"Publish on"),
                                       widget=forms.DateInput({"class": "date",
                                                               "size": "11",
                                                               "maxlength": "11",
                                                               }, format="%d.%m.%Y"))
    publication_time = forms.TimeField(required=False,
                                       label=_(u"Publication time"),
                                       widget=forms.TimeInput({"class": "time",
                                                               "size": "5",
                                                               "maxlength": "5",
                                                               }, format="%H:%M"))
    disable_comments = forms.BooleanField(required=False, initial=False, 
                                          label=_(u"Disable comments"),                                          
                                          widget=forms.CheckboxInput({"class": "checkbox"}))
    hide_comments = forms.BooleanField(required=False, initial=False,
                                       label=_(u"Hide comments"),
                                       widget=forms.CheckboxInput({"class": "checkbox"}))
    include_in_rss = forms.BooleanField(required=False, initial=True,
                                        label=_(u"Include in RSS"),
                                        widget=forms.CheckboxInput({"class": "checkbox"}))

    tags = TagField(required=False, label=_(u"Tags"),
                    widget=forms.TextInput({"class": "tags",
                                            "placeholder": _(u"Tags")}))
    
    def __init__(self, *args, **kwargs):
        #noinspection PyArgumentEqualDefault
        self.instance = kwargs.pop("instance", None)
        if self.instance:
            initial = kwargs.pop("initial", {})
            initial['title'] = self.instance.title
            initial['slug'] = self.instance.slug
            initial['text'] = self.instance.text
            initial['markdown'] = self.instance.markdown
            initial['published'] = self.instance.published
            initial['publication_date'] = self.instance.publication_timestamp and self.instance.publication_timestamp.date() 
            initial['publication_time'] = self.instance.publication_timestamp and self.instance.publication_timestamp.time()
            initial['images'] = [image.id for image in Image.objects.filter(entry=self.instance)]
            initial['disable_comments'] = self.instance.disable_comments
            initial['hide_comments'] = self.instance.hide_comments
            initial['include_in_rss'] = self.instance.include_in_rss
            initial['tags'] = edit_string_for_tags(Tag.objects.get_for_object(self.instance))
            kwargs["initial"] = initial
        super(EntryForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        if not self.instance:
            return None
        data = self.cleaned_data
        self.instance.title = data.get('title')
        slug = data.get('slug')
        if slug:
            self.instance.slug = slug
        self.instance.text = data.get('text')
        self.instance.markdown = data.get('markdown')
        self.instance.published = data.get('published', False)
        publication_date = data.get('publication_date')
        publication_time = data.get('publication_time')
        now = datetime.datetime.now()
        if self.instance.published and not publication_date:
            publication_date = now.date()
        if self.instance.published and not publication_time:
            publication_time = now.time()
        if publication_date and publication_time:
            self.instance.publication_timestamp = datetime.datetime.combine(publication_date, publication_time)
        self.instance.disable_comments = data.get('disable_comments', False)
        self.instance.hide_comments = data.get('hide_comments', False)
        self.instance.include_in_rss = data.get('include_in_rss', False)
        if commit:
            self.instance.save()
        images = data.get("images", [])
        if images:
            for image_id in images:
                image = Image.objects.get(pk=int(image_id))
                if image.entry != self.instance:
                    image.entry = self.instance
                    image.save()
        Tag.objects.update_tags(self.instance, data.get('tags'))
        return self.instance


class BlogAuthorCommentForm(ModelForm):

    success_message = _(u"Your comment was added.")
    error_message = _(u"Please correct the indicated errors.")

    parent = forms.ModelChoiceField(queryset=Comment.objects.all(),
                                    required=False,
                                    widget=forms.HiddenInput())

    text = forms.CharField(required=True, widget=forms.Textarea(),
                           label=_(u"Text"),
                           help_text=_("""You can use <a class="dashed markdown" href="#">Markdown</a> here."""))

    class Meta:
        model = Comment
        fields = ["parent", "text"]


class CommentForm(BlogAuthorCommentForm):

    author_name = forms.CharField(required=True, label=_(u"Your name"),
                                  widget=forms.TextInput())
    author_email = forms.EmailField(required=False, label=_(u"Your email"),
                                    widget=forms.TextInput(),
                                    help_text=_("Optional. Used to get your Gravatar."))
    author_url = forms.URLField(required=False, label=_(u"Your site URL"),
                                widget=forms.TextInput(),
                                help_text=_("Optional."))

    notify = forms.BooleanField(required=False, label=_(u"Notify on replies by email"),
                                widget=forms.CheckboxInput())

    class Meta:
        model = Comment
        fields = ["parent", "text", "author_name", "author_email",
                  "author_url", "notify"]

apps/blog/views/comments.py
from annoying.decorators import JsonResponse, ajax_request
from blog.forms import CommentForm, BlogAuthorCommentForm
from blog.models import Entry, Comment
from blog.views import BlogViewMixin
from django.conf import settings
from django.contrib import messages
from django.contrib.sites.models import Site
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.template import Context
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from django.views.generic import View


AUTHOR_NAME_COOKIE = "comment_author_name"
AUTHOR_EMAIL_COOKIE = "comment_author_email"
AUTHOR_URL_COOKIE = "comment_author_url"
NOTIFY_COOKIE = "comment_notify"
COOKIE_MAX_AGE = 60 * 60 * 24 * 30


class AddComment(BlogViewMixin, View):

    #noinspection PyUnusedLocal
    def post(self, request, *args, **kwargs):
        entry_id = kwargs["entry_id"]
        entry = get_object_or_404(Entry, id=entry_id, published=True)
        if self.is_author:
            form = BlogAuthorCommentForm(request.POST,
                                        instance=Comment(entry=entry,
                                                         by_blog_author=True))
        else:
            form = CommentForm(request.POST, instance=Comment(entry=entry))
        cookies = {}

        if form.is_valid():
            comment = form.save()
            comment.check_for_spam(request)
            parent = comment.parent
            context = self.get_context_data(**kwargs)
            context["comment"] = comment
            response = dict(status="success", message=unicode(form.success_message),
                            comment=render_to_string("blog/include/comment.html",
                                                     Context(context)))

            if not self.is_author:
                cookies[AUTHOR_NAME_COOKIE] = form.cleaned_data['author_name']
                cookies[AUTHOR_EMAIL_COOKIE] = form.cleaned_data['author_email']
                cookies[AUTHOR_URL_COOKIE] = form.cleaned_data['author_url']
                cookies[NOTIFY_COOKIE] = form.cleaned_data['notify'] and u"1" or u""

                # Send notification to author
                if not comment.is_spam:
                    link = "http://%s%s#comment%i" % (Site.objects.get_current().domain,
                                                      entry.get_absolute_url(),
                                                      comment.id)
                    message_text = render_to_string("blog/email/author-notification.html",
                                                    Context(dict(comment=comment,
                                                                 link=link,
                                                                 entry=entry,
                                                                 blog=self.blog)))
                    message = EmailMessage(subject=_(u'New comment to \xab%(title)s\xbb') % dict(title=entry.title),
                                           body=message_text,
                                           to=[self.blog.author.email],
                                           from_email=settings.DEFAULT_FROM_EMAIL)
                    message.content_subtype = "html"
                    message.send(fail_silently=True)

            if not comment.is_spam and parent and parent.notify and parent.author_email and parent.author_email != comment.author_email:
                link = "http://%s%s#comment%i" % (Site.objects.get_current().domain,
                                                  entry.get_absolute_url(),
                                                  comment.id)
                unsubscribe_link = "http://%s%s" % (Site.objects.get_current().domain,
                                                  reverse("blog:unsubscribe_from_notifications",
                                                          kwargs=dict(comment_id=parent.id,
                                                                      secret=parent.secret)))
                message_text = render_to_string("blog/email/reply-notification.html",
                                                Context(dict(parent=parent,
                                                             comment=comment,
                                                             link=link,
                                                             unsubscribe_link=unsubscribe_link,
                                                             entry=entry,
                                                             blog=self.blog)))
                message = EmailMessage(subject=_(u'New reply to your comment for \xab%(title)s\xbb') % dict(title=entry.title),
                                       body=message_text,
                                       to=[parent.author_email],
                                       from_email=settings.DEFAULT_FROM_EMAIL)
                message.content_subtype = "html"
                message.send(fail_silently=True)


        else:
            errors = {}
            #noinspection PyUnresolvedReferences
            for field_name, errors_list in form.errors.items():
                errors[field_name] = errors_list[0]
            response = dict(status="error", errors=errors,
                            message=unicode(form.error_message))

        response = JsonResponse(response)
        if cookies:
            for k, v in cookies.items():
                response.set_cookie(k, v.encode('utf-8'), COOKIE_MAX_AGE)

        return response


class DeleteComment(BlogViewMixin, View):

    #noinspection PyUnusedLocal
    @method_decorator(ajax_request)
    def post(self, request, *args, **kwargs):
        if not self.is_author:
            return HttpResponseForbidden()
        comment_id = kwargs["comment_id"]
        comment = get_object_or_404(Comment, id=int(comment_id))
        comment.delete()
        return dict(status="success",
                    spam_count=self.blog.spam_comments().count())


class Unsubscribe(BlogViewMixin, View):

    #noinspection PyUnusedLocal
    def get(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, id=int(kwargs["comment_id"]),
                                    secret=kwargs["secret"])
        comment.notify = False
        comment.save()
        messages.success(request, _(u"You were unsubscribed from reply notifications for this comment."))
        return redirect(comment.entry)

apps/blog/templates/blog/include/about.html
{% load i18n %}
{% load utils %}
<section id="about" class="about clearfix" itemscope itemtype="http://schema.org/Person">
  <h1>{% trans "About me" %}</h1>
  <img src="{{ STATIC_URL }}images/author.jpg" itemprop="photo" alt="{{ blog.author_name }}" width="140" height="140" />
  <p>
    {% localized_flatblock "about-short" %} <br/>
    <a href="{% url about %}" rel="author">{% trans "More..." %}</a>
  </p>
</section>

apps/blog/templates/blog/include/author-panel.html
{% load i18n %}
{% if is_author %}
<nav class="author-panel">
  <ul>
    <li><a href="{% url blog:admin_add_entry %}">{% trans "New entry" %}</a></li>
    {% with blog.spam_comments.count as count %}
      {% if count %}
        <li><a href="{% url blog:admin_spam %}">{% trans "Spam" %} (<span id="spam-counter">{{ count }}</span>)</a></li>
      {% endif %}
    {% endwith %}
    <li><a href="{% url blog:admin_index %}">{% trans "Entries list" %}</a></li>
    {% if request.user.is_staff %}
    <li><a href="{% url admin:index %}">{% trans "Django admin" %}</a></li>
    {% endif %}
    <li class="right"><a href="{% url logout %}?next={{ blog.get_absolute_url }}">{% trans "Log out" %}</a></li>
  </ul>
</nav>
{% endif %}

apps/blog/templates/blog/include/comment-form.html
{% load i18n %}
<form id="comment-form" action="{% url blog:add_comment entry_id=entry.id %}" method="post">
  {{ form.parent }}
  
  <div class="field text">
    {{ form.text.label_tag }}
    <div class="errors"></div>
    {{ form.text }}
    <label for="id_preview"><input type="checkbox" id="id_preview" /> {% trans "Preview" %}</label>
    <div class="help">
      {{ form.text.help_text|safe }}
    </div>
    <div id="preview-area"></div>
  </div>

  <div style="display: none;" id="markdown-help">{% filter linebreaksbr %}{% blocktrans %}This is a paragraph, which is text surrounded by whitespace. Paragraphs can be on one
line (or many), and can drone on for hours.

Here is a Markdown link to [Google](http://google.com), and a literal.

Now some inline markup like _italics_,  **bold**, and `code()`.

> Blockquotes are like quoted text in email replies
>> And, they can be nested

* Bullet lists are easy too

1. A numbered list

And now some code:

&nbsp;&nbsp;&nbsp;&nbsp;// Code is just text indented a bit
&nbsp;&nbsp;&nbsp;&nbsp;which(is_easy) to_remember();
{% endblocktrans %}{% endfilter %}</div>

  {% if not is_author %}
    <div class="field name">
      {{ form.author_name.label_tag }}
      <div class="errors"></div>
      {{ form.author_name }}
      <div class="help">
        &nbsp;{{ form.author_name.help_text }}
      </div>
    </div>

    <div class="field email">
      {{ form.author_email.label_tag }}
      <div class="errors"></div>
      {{ form.author_email }}
      <div class="help">
        {{ form.author_email.help_text }}
      </div>
    </div>


    <div class="field url">
      {{ form.author_url.label_tag }}
      <div class="errors"></div>
      {{ form.author_url }}
      <div class="help">
        {{ form.author_url.help_text }}
      </div>
    </div>

  {% endif %}
  
  <div class="buttons">
    <label for="id_notify">{{ form.notify }} {{ form.notify.label }}</label>
    <span class="indicator"></span>
    <input type="submit" value="{% trans "Submit" %}" />
  </div>
</form>

apps/blog/templates/blog/include/comment.html
{% load i18n %}
{% load blog_tags %}
{% load simplegravatar %}
{% load markup %}
<article class="comment lvl{{ comment.level }} {% if comment.by_blog_author %}by-author{% endif %}"
         data-id="{{ comment.id }}" data-lvl="{{ comment.level }}"
         id="comment{{ comment.id }}">
  <header>
    {% if comment.by_blog_author %}
      {% show_gravatar blog.author.email 20 %}
      <span class="author">
        <a href="{{ blog_absolute_uri }}">{{ blog.author_name }}</a>
      </span>
    {% else %}
      {% show_gravatar comment.author_email 20 %}
      <span class="author">
        {% if comment.author_url %}
          <a href="{{ comment.author_url }}" rel="nofollow">{{ comment.author_name }}</a>
        {% else %}
          {{ comment.author_name }}
        {% endif %}
      </span>
    {% endif %}
    <time class="clearfix" datetime="{{ comment.timestamp|date:"c" }}">{{ comment.timestamp|humanized_date }}</time>
  </header>
  {{ comment.text|markdown:"codehilite" }}
  <footer>
    <ul>
      {% if is_author %}
        <li><a class="delete dashed" href="{% url blog:delete_comment comment_id=comment.id %}">{% trans "Delete" %}</a></li>
      {% endif %}
{#      <li><a class="reply dashed" href="#comment{{ comment.id }}">{% trans "Reply" %}</a></li>#}
    </ul>
  </footer>
</article>

apps/blog/templates/blog/include/css.html
{% load compress %}
{% load less %}

{% if debug %}
  <link rel="stylesheet" href="{{ STATIC_URL }}javascripts/jquery/fancybox/jquery.fancybox-1.3.4.css" />
{% else %}
  <link rel="stylesheet" href="http://yandex.st/jquery/fancybox/1.3.4/jquery.fancybox.css" />
{% endif %}

{% compress css %}
  <link rel="stylesheet" href="{{ STATIC_URL }}javascripts/jquery/jquery.qtip.css" />
  <link rel="stylesheet" href="{{ STATIC_URL }}javascripts/jquery/jquery.qtip.css" />
  <link rel="stylesheet" href="{{ STATIC_URL }}javascripts/jquery/apprise.css" />
  <link rel="stylesheet" href="{{ STATIC_URL }}javascripts/jquery/fotorama.css" />
  <link rel="stylesheet" href="{{ STATIC_URL }}{% less "styles/blog/blog.less" %}" />
  <link rel="stylesheet" href="{{ STATIC_URL }}styles/codehilite.css" />
{% endcompress %}

{% include "include/fonts.html" %}

<!--[if lt IE 9 ]>
  <link rel="stylesheet" href="{{ STATIC_URL }}{% less "styles/blog/ie.less" %}" />
<![endif]-->
<!--[if lt IE 8 ]>
  <link rel="stylesheet" href="{{ STATIC_URL }}{% less "styles/blog/ie7.less" %}" />
<![endif]-->

apps/blog/templates/blog/include/entries-list.html
{% load i18n %}
{% load blog_tags %}
{% if request.is_ajax %}
  <title>{% if page_title %}{{ page_title }} | {% endif %}{{ blog.title }}</title>
{% endif %}
{% for entry in entries %}
  <article class="entry">
    <header>
      <h1><a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a></h1>
      {% if is_author %}
        <a class="edit" href="{% url blog:admin_edit_entry entry.id %}">{% trans "Edit" %}</a>
      {% endif %}
      <div class="timestamp">
        {% trans "Published on" %} <time datetime="{{ entry.publication_timestamp|date:"c" }}Z" pubdate>{{ entry.publication_timestamp|humanized_date }}</time>
      </div>
    </header>
    {{ entry.short_text }}
    {% spaceless %}
    <footer>
      {% if entry.tags.exists %}
      {% trans "Tags" %}:
      <ul>
        {% for tag in entry.tags %}
          <li><a href="{% url blog:index tag=tag.name %}">{{ tag }}</a></li>
        {% endfor %}
      </ul>
      {% endif %}
      <div class="right">
        <div class="share-icons" data-url="{{ entry.absolute_uri }}" data-title="{{ entry.title }}"></div>
        <a href="{{ entry.get_absolute_url }}#comments" class="comments">
          {% with entry.comments_count as comments_count %}
            {% if comments_count %}
              {% blocktrans count count=comments_count %}{{ count }} comment{% plural %}{{ count }} comments{% endblocktrans %}
            {% else %}
              {% trans "No comments" %}
            {% endif %}
          {% endwith %}
        </a>
      </div>
    </footer>
    {% endspaceless %}
  </article>

{% endfor %}

<nav class="pages">
  <a class="prev" {% if not prev_page %}style="display: none;"{% endif %} href="{{ prev_page }}">&larr; <span>{% trans "Previous page" %}</span></a>
  <a class="next" {% if not next_page %}style="display: none;"{% endif %} href="{{ next_page }}"><span>{% trans "Next page" %}</span> &rarr;</a>
</nav>

apps/blog/templates/blog/include/js.html
{% load compress %}
{% load coffeescript %}

{% if debug %}
  <script src="{{ STATIC_URL }}javascripts/jquery/jquery.min.js"></script>
  <script src="{{ STATIC_URL }}javascripts/jquery/ui/jquery.effects.core.js"></script>
  <script src="{{ STATIC_URL }}javascripts/jquery/ui/jquery.effects.drop.js"></script>
  <script src="{{ STATIC_URL }}javascripts/jquery/ui/jquery.effects.bounce.js"></script>
  <script src="{{ STATIC_URL }}javascripts/jquery/fancybox/jquery.fancybox-1.3.4.js"></script>
{% else %}
  <script src="http://yandex.st/jquery/1.6.2/jquery.min.js"></script>
  <script src="http://yandex.st/jquery-ui/1.8.11/jquery.effects.core.js"></script>
  <script src="http://yandex.st/jquery-ui/1.8.11/jquery.effects.drop.js"></script>
  <script src="http://yandex.st/jquery-ui/1.8.11/jquery.effects.bounce.js"></script>
  <script src="http://yandex.st/jquery/fancybox/1.3.4/jquery.fancybox.min.js"></script>
{% endif %}

<script src="{% url i18n.js %}"></script>

<!--[if lt IE 9]>
{% if debug %}
  <script src="{{ STATIC_URL }}javascripts/jquery/json2.js"></script>
{% else %}
  <script src="http://yandex.st/json2/2011-01-18/json2.min.js"></script>
{% endif %}
<![endif]-->

{% compress js %}
  <script src="{{ STATIC_URL }}javascripts/jquery/spin.js"></script>
  <script src="{{ STATIC_URL }}javascripts/jquery/jquery.pjax.js"></script>
  <script src="{{ STATIC_URL }}javascripts/jquery/jquery.validate.js"></script>
  <script src="{{ STATIC_URL }}javascripts/jquery/jquery.qtip.js"></script>
  <script src="{{ STATIC_URL }}javascripts/jquery/jquery.textareaPreview.js"></script>
  <script src="{{ STATIC_URL }}javascripts/jquery/apprise.js"></script>
  <script src="{{ STATIC_URL }}javascripts/jquery/fotorama.js"></script>
  <script src="{{ STATIC_URL }}javascripts/showdown/showdown.js"></script>
  <script src="{{ STATIC_URL }}{% coffeescript "javascripts/login.coffee" %}"></script>
  <script src="{{ STATIC_URL }}{% coffeescript "javascripts/blog/blog.coffee" %}"></script>
  <script>
    {% inlinecoffeescript %}
      $(->
        window.init_login_box()
      )
    {% endinlinecoffeescript %}
  </script>
{% endcompress %}

apps/blog/templates/blog/include/locale-switcher.html
{% for blog in blogs %}
  <a href="{{ blog.get_absolute_url }}">{{ blog.message }}</a>
{% endfor %}

apps/blog/templates/blog/include/navigation.html
{% load i18n %}
<nav>
  <ul>
    {% if not is_frontpage and not is_about_page %}
      <li><a href="{% url about %}" rel="author">{% trans "About" %}</a></li>
    {% endif %}
    <li><a href="{% url blog:archive %}">{% trans "Archive" %}</a></li>
    <li><a href="{% url blog:tags %}">{% trans "Tags" %}</a></li>
    {% if blog.feed_url %}
      <li class="rss"><a href="{{ blog.feed_url }}">{% trans "RSS" %}</a></li>
    {% endif %}
  </ul>
</nav>

apps/blog/templates/blog/include/plusone-script.html
<script type="text/javascript">
  window.___gcfg = {lang: '{% if request.LANGUAGE_CODE != "en" %}{{ request.LANGUAGE_CODE }}{% endif %}'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>

apps/blog/templates/blog/include/search.html
{% load i18n %}
<form name="search" class="search" method="get" action="{% url blog:search %}">
  <input name="q" type="search" value="{{ search_term }}" placeholder="{% trans "Search" %}" />
</form>

apps/blog/templates/blog/include/status-messages.html
<div id="status-messages">
{% if messages %}
  {% for message in messages %}
    <div class="message{% if message.tags %} {{ message.tags }}"{% endif %}>{{ message }}</div>
  {% endfor %}
{% endif %}
</div>